name: Docker Image Build

on:
  push:
    branches: [ main ]
    tags: [ v* ]

jobs:
  aspia-router:
    uses: ./.github/workflows/docker-image-template.yml
    with:
      image: aspia-router
    secrets: inherit
  aspia-relay:
    uses: ./.github/workflows/docker-image-template.yml
    with:
      image: aspia-relay
    secrets: inherit
